//
//  SharedModels.swift
//  NextBus
//
//  Shared models, networking, and data persistence used by both the main app
//  and the NextBusWidget extension.
//
//  To share this file with the widget target:
//    Select SharedModels.swift in Xcode → File Inspector → Target Membership → check NextBusWidget
//

import Foundation
import Compression
import CoreLocation

// MARK: - App Group Configuration

let appGroupID = "group.tejaspatel.NextBus"

var sharedDefaults: UserDefaults {
    UserDefaults(suiteName: appGroupID) ?? .standard
}

// MARK: - User settings

struct UserStopConfig: Identifiable, Codable, Hashable {
    var id: String            // stop code
    var label: String         // user label
    var selectedRoutes: Set<String> = [] // empty means all
    var headsignIncludes: String = ""   // optional contains filter
    var enabled: Bool = true
    var stopLat: Double?      // stop latitude (from stops.txt)
    var stopLon: Double?      // stop longitude (from stops.txt)
}

let USER_STOPS_KEY = "userStops.v1"
let USE_CUSTOM_STOPS_ONLY_KEY = "useCustomStopsOnly.v1"

let GTFS_RT_URL_STRING = "https://bustracker.sbmtd.gov/gtfsrt/vehicles"

func loadUserStops() -> [UserStopConfig] {
    if let data = sharedDefaults.data(forKey: USER_STOPS_KEY) {
        if let decoded = try? JSONDecoder().decode([UserStopConfig].self, from: data) {
            return decoded
        }
    }
    return []
}

func saveUserStops(_ stops: [UserStopConfig]) {
    if let data = try? JSONEncoder().encode(stops) {
        sharedDefaults.set(data, forKey: USER_STOPS_KEY)
    }
}

func loadUseCustomStopsOnly() -> Bool {
    sharedDefaults.bool(forKey: USE_CUSTOM_STOPS_ONLY_KEY)
}

func saveUseCustomStopsOnly(_ flag: Bool) {
    sharedDefaults.set(flag, forKey: USE_CUSTOM_STOPS_ONLY_KEY)
}

// MARK: - UserDefaults migration (standard → App Group)

private let MIGRATION_KEY = "didMigrateToAppGroup.v1"

/// Copies user stops from UserDefaults.standard to the App Group suite if not done yet.
func migrateUserDefaultsToAppGroupIfNeeded() {
    guard !sharedDefaults.bool(forKey: MIGRATION_KEY) else { return }
    // If App Group already has data, skip
    if sharedDefaults.data(forKey: USER_STOPS_KEY) != nil {
        sharedDefaults.set(true, forKey: MIGRATION_KEY)
        return
    }
    // Copy from standard defaults
    if let data = UserDefaults.standard.data(forKey: USER_STOPS_KEY) {
        sharedDefaults.set(data, forKey: USER_STOPS_KEY)
    }
    if UserDefaults.standard.object(forKey: USE_CUSTOM_STOPS_ONLY_KEY) != nil {
        sharedDefaults.set(UserDefaults.standard.bool(forKey: USE_CUSTOM_STOPS_ONLY_KEY), forKey: USE_CUSTOM_STOPS_ONLY_KEY)
    }
    sharedDefaults.set(true, forKey: MIGRATION_KEY)
}

// MARK: - Stop coordinate lookup (from bundled stops.txt)

/// All 627 SBMTD stop coordinates, parsed from stops.txt via csv.reader for accuracy.
/// Generated by script — do not hand-edit.
private let embeddedStopCoordinates: [String: (lat: Double, lon: Double)] = [
    "1": (34.424858, -119.726070),     "2": (34.420714, -119.718940),
    "3": (34.415231, -119.708745),     "4": (34.420949, -119.703600),
    "7": (34.424932, -119.682200),     "8": (34.428849, -119.676590),
    "9": (34.422963, -119.668508),     "10": (34.424216, -119.682260),
    "12": (34.420618, -119.718609),     "14": (34.430419, -119.731200),
    "15": (34.440496, -119.734617),     "16": (34.440577, -119.751500),
    "17": (34.440493, -119.737300),     "19": (34.419119, -119.743170),
    "20": (34.404222, -119.742969),     "21": (34.401329, -119.721618),
    "22": (34.406762, -119.701296),     "23": (34.406724, -119.700626),
    "24": (34.436539, -119.788930),     "25": (34.435562, -119.821100),
    "26": (34.429643, -119.869890),     "27": (34.428798, -119.875665),
    "28": (34.430076, -119.868335),     "29": (34.440260, -119.733790),
    "31": (34.442769, -119.791352),     "32": (34.445418, -119.807482),
    "33": (34.442278, -119.830788),     "35": (34.443077, -119.830190),
    "37": (34.451570, -119.831161),     "39": (34.451252, -119.789790),
    "40": (34.451401, -119.760224),     "42": (34.414984, -119.848091),
    "43": (34.434937, -119.900585),     "44": (34.423675, -119.695062),
    "45": (34.425403, -119.684260),     "46": (34.422065, -119.651580),
    "47": (34.437115, -119.632571),     "48": (34.436046, -119.601892),
    "49": (34.422348, -119.614727),     "50": (34.424230, -119.631480),
    "51": (34.417280, -119.865970),     "53": (34.414157, -119.707216),
    "54": (34.414036, -119.707424),     "55": (34.416422, -119.740906),
    "56": (34.403759, -119.731146),     "58": (34.426174, -119.687958),
    "59": (34.416935, -119.858780),     "60": (34.415140, -119.862637),
    "63": (34.414885, -119.697468),     "64": (34.411069, -119.697841),
    "67": (34.446617, -119.790411),     "68": (34.451387, -119.758635),
    "69": (34.430451, -119.791498),     "70": (34.430403, -119.802272),
    "72": (34.448986, -119.835970),     "75": (34.410384, -119.699705),
    "77": (34.436588, -119.898208),     "78": (34.439787, -119.892721),
    "79": (34.429663, -119.892777),     "82": (34.451331, -119.830168),
    "83": (34.451575, -119.760153),     "84": (34.440101, -119.789225),
    "85": (34.435111, -119.810010),     "87": (34.439699, -119.771946),
    "89": (34.427564, -119.746890),     "90": (34.429115, -119.742034),
    "92": (34.417525, -119.868010),     "95": (34.421634, -119.600844),
    "96": (34.401673, -119.525869),     "97": (34.396497, -119.515319),
    "98": (34.385270, -119.486667),     "99": (34.394268, -119.512994),
    "100": (34.404568, -119.526952),     "102": (34.406224, -119.541470),
    "103": (34.396167, -119.515217),     "104": (34.425301, -119.702300),
    "108": (34.429107, -119.869520),     "109": (34.430926, -119.905809),
    "110": (34.429755, -119.885153),     "114": (34.440992, -119.821200),
    "115": (34.422712, -119.714359),     "116": (34.412440, -119.688752),
    "118": (34.411995, -119.689620),     "119": (34.419212, -119.668380),
    "120": (34.403927, -119.694742),     "123": (34.404640, -119.526646),
    "126": (34.424080, -119.702950),     "128": (34.427305, -119.679680),
    "136": (34.451353, -119.776096),     "143": (34.434793, -119.900439),
    "144": (34.429922, -119.877150),     "153": (34.422940, -119.691368),
    "156": (34.440346, -119.750451),     "157": (34.436526, -119.790320),
    "164": (34.442933, -119.829880),     "173": (34.430584, -119.714463),
    "174": (34.427032, -119.686480),     "175": (34.420324, -119.697800),
    "180": (34.431494, -119.848003),     "181": (34.435965, -119.827030),
    "182": (34.419634, -119.692400),     "183": (34.423543, -119.704170),
    "184": (34.422275, -119.700476),     "186": (34.418086, -119.696527),
    "187": (34.413878, -119.698725),     "189": (34.409497, -119.698830),
    "190": (34.404503, -119.705358),     "191": (34.402642, -119.708393),
    "192": (34.401757, -119.710743),     "193": (34.401259, -119.713493),
    "194": (34.401004, -119.719046),     "195": (34.402770, -119.721382),
    "196": (34.404784, -119.721766),     "197": (34.408622, -119.721069),
    "198": (34.409605, -119.717923),     "199": (34.411170, -119.715256),
    "200": (34.417948, -119.705811),     "203": (34.422295, -119.701154),
    "206": (34.414359, -119.713332),     "208": (34.402118, -119.721999),
    "209": (34.400847, -119.719197),     "210": (34.400904, -119.714570),
    "211": (34.401672, -119.710108),     "212": (34.404380, -119.705176),
    "213": (34.416063, -119.696944),     "216": (34.422707, -119.706050),
    "217": (34.424399, -119.707890),     "218": (34.423623, -119.727609),
    "219": (34.422462, -119.723394),     "220": (34.422456, -119.721122),
    "221": (34.419051, -119.716484),     "222": (34.417937, -119.714983),
    "223": (34.416164, -119.712482),     "224": (34.414910, -119.710221),
    "225": (34.424457, -119.723035),     "227": (34.426336, -119.701460),
    "228": (34.428424, -119.699169),     "229": (34.431842, -119.692830),
    "230": (34.429679, -119.690090),     "231": (34.429383, -119.689330),
    "233": (34.426302, -119.672700),     "234": (34.427540, -119.674540),
    "235": (34.424751, -119.670520),     "236": (34.420955, -119.670648),
    "237": (34.421116, -119.672963),     "238": (34.422747, -119.675242),
    "239": (34.421332, -119.678330),     "240": (34.422752, -119.680270),
    "241": (34.426609, -119.685580),     "242": (34.428407, -119.688030),
    "243": (34.431839, -119.695560),     "244": (34.425561, -119.707337),
    "245": (34.427340, -119.709783),     "246": (34.428290, -119.711070),
    "247": (34.429224, -119.712347),     "248": (34.433564, -119.718274),
    "249": (34.435694, -119.721195),     "250": (34.436688, -119.722534),
    "251": (34.438141, -119.724501),     "252": (34.440475, -119.728022),
    "253": (34.440480, -119.730727),     "254": (34.440332, -119.737170),
    "255": (34.440535, -119.740565),     "256": (34.440555, -119.747010),
    "257": (34.440689, -119.760500),     "258": (34.440027, -119.771430),
    "259": (34.439368, -119.774740),     "260": (34.438878, -119.777638),
    "261": (34.438058, -119.782010),     "262": (34.437568, -119.783424),
    "263": (34.435412, -119.794900),     "264": (34.434737, -119.801836),
    "265": (34.435071, -119.807000),     "266": (34.434861, -119.809438),
    "268": (34.435448, -119.817410),     "269": (34.435772, -119.823890),
    "270": (34.436151, -119.829350),     "271": (34.434350, -119.835804),
    "272": (34.433550, -119.838940),     "273": (34.432855, -119.841708),
    "274": (34.431927, -119.845667),     "276": (34.431171, -119.849878),
    "277": (34.430963, -119.853649),     "278": (34.430791, -119.857232),
    "279": (34.430332, -119.859090),     "280": (34.430373, -119.863106),
    "281": (34.428296, -119.869870),     "282": (34.426751, -119.871456),
    "283": (34.426765, -119.873336),     "284": (34.429980, -119.872498),
    "285": (34.431265, -119.847942),     "286": (34.433440, -119.838328),
    "287": (34.434283, -119.835058),     "288": (34.435679, -119.831435),
    "289": (34.435713, -119.826232),     "290": (34.435557, -119.823499),
    "291": (34.434794, -119.805700),     "292": (34.434875, -119.797810),
    "293": (34.437948, -119.781390),     "294": (34.440444, -119.762261),
    "295": (34.440338, -119.744152),     "296": (34.440275, -119.731200),
    "297": (34.432512, -119.717131),     "298": (34.429668, -119.713254),
    "299": (34.426135, -119.705740),     "300": (34.419746, -119.709916),
    "307": (34.441200, -119.821490),     "308": (34.441866, -119.827620),
    "312": (34.430059, -119.883330),     "313": (34.429900, -119.891768),
    "314": (34.429868, -119.894051),     "315": (34.429581, -119.897021),
    "318": (34.421325, -119.678681),     "319": (34.419438, -119.676090),
    "320": (34.421588, -119.647720),     "321": (34.421177, -119.644520),
    "322": (34.421425, -119.640240),     "323": (34.401699, -119.523764),
    "324": (34.421453, -119.641890),     "325": (34.428849, -119.688960),
    "326": (34.418270, -119.674390),     "327": (34.429425, -119.720442),
    "328": (34.428638, -119.726334),     "329": (34.427401, -119.727670),
    "330": (34.432418, -119.733491),     "332": (34.428341, -119.716556),
    "333": (34.426636, -119.714234),     "334": (34.424080, -119.710755),
    "335": (34.421923, -119.656070),     "336": (34.417475, -119.854100),
    "342": (34.394512, -119.512969),     "343": (34.416850, -119.698029),
    "345": (34.419707, -119.701911),     "346": (34.418280, -119.702792),
    "347": (34.416346, -119.700165),     "348": (34.414820, -119.698083),
    "349": (34.403185, -119.728353),     "350": (34.403665, -119.730040),
    "351": (34.404807, -119.740594),     "353": (34.412794, -119.740149),
    "354": (34.416021, -119.740522),     "355": (34.425646, -119.744043),
    "356": (34.425157, -119.747585),     "357": (34.423413, -119.749420),
    "358": (34.422360, -119.749823),     "359": (34.425660, -119.750962),
    "360": (34.429690, -119.748472),     "361": (34.430206, -119.749886),
    "362": (34.432555, -119.748132),     "363": (34.435694, -119.751390),
    "364": (34.439005, -119.749077),     "365": (34.431797, -119.748967),
    "366": (34.429359, -119.748507),     "367": (34.425016, -119.743721),
    "368": (34.405024, -119.738812),     "369": (34.402942, -119.728196),
    "370": (34.402281, -119.725792),     "371": (34.419847, -119.869891),
    "372": (34.422113, -119.869622),     "373": (34.424544, -119.869560),
    "374": (34.426655, -119.869665),     "382": (34.432549, -119.789752),
    "386": (34.414199, -119.687177),     "389": (34.424463, -119.708502),
    "390": (34.424865, -119.712054),     "391": (34.412119, -119.704602),
    "392": (34.411041, -119.701587),     "394": (34.420357, -119.707750),
    "395": (34.421286, -119.709276),     "396": (34.423188, -119.711885),
    "397": (34.424806, -119.714087),     "398": (34.425984, -119.715688),
    "399": (34.427494, -119.717737),     "400": (34.427472, -119.729078),
    "401": (34.435694, -119.733774),     "402": (34.439669, -119.744548),
    "403": (34.436153, -119.745070),     "404": (34.433248, -119.746260),
    "405": (34.436443, -119.750279),     "406": (34.427741, -119.729490),
    "407": (34.421910, -119.707743),     "408": (34.421040, -119.706556),
    "409": (34.441460, -119.757619),     "410": (34.441271, -119.764407),
    "411": (34.441543, -119.769105),     "414": (34.442635, -119.782397),
    "415": (34.443910, -119.789963),     "416": (34.442051, -119.795891),
    "417": (34.442712, -119.797205),     "418": (34.445263, -119.797435),
    "419": (34.445314, -119.803244),     "420": (34.443889, -119.808820),
    "421": (34.441909, -119.815370),     "422": (34.442434, -119.758396),
    "423": (34.444151, -119.757862),     "424": (34.444146, -119.754122),
    "425": (34.443928, -119.751158),     "426": (34.441747, -119.751172),
    "427": (34.418704, -119.693400),     "428": (34.421204, -119.690750),
    "429": (34.423311, -119.688480),     "430": (34.424338, -119.687420),
    "431": (34.426025, -119.685620),     "432": (34.420477, -119.596920),
    "433": (34.419761, -119.594414),     "434": (34.419285, -119.591944),
    "435": (34.417682, -119.582760),     "436": (34.416091, -119.575330),
    "437": (34.416756, -119.569160),     "438": (34.416457, -119.560360),
    "439": (34.414723, -119.557456),     "440": (34.411364, -119.552148),
    "441": (34.407272, -119.547424),     "442": (34.405982, -119.539490),
    "443": (34.405358, -119.535461),     "445": (34.404844, -119.529742),
    "447": (34.399916, -119.519411),     "448": (34.397754, -119.517100),
    "450": (34.392476, -119.510823),     "452": (34.387138, -119.498041),
    "453": (34.386733, -119.494256),     "454": (34.385646, -119.490855),
    "455": (34.383217, -119.485923),     "456": (34.384345, -119.480564),
    "457": (34.384764, -119.484430),     "458": (34.387670, -119.494427),
    "459": (34.389081, -119.497141),     "460": (34.398231, -119.517411),
    "462": (34.421410, -119.598879),     "463": (34.424231, -119.685380),
    "464": (34.422027, -119.687734),     "465": (34.419972, -119.689930),
    "466": (34.418458, -119.691550),     "467": (34.415358, -119.694870),
    "468": (34.419463, -119.696654),     "469": (34.435686, -119.872737),
    "470": (34.436497, -119.876590),     "471": (34.436998, -119.883539),
    "472": (34.433845, -119.885156),     "473": (34.432815, -119.889519),
    "474": (34.433929, -119.891433),     "475": (34.437387, -119.892675),
    "476": (34.439095, -119.894743),     "477": (34.437024, -119.895314),
    "479": (34.432722, -119.902647),     "480": (34.440107, -119.894097),
    "481": (34.434242, -119.891816),     "482": (34.432902, -119.891197),
    "483": (34.436611, -119.883260),     "484": (34.436375, -119.878362),
    "485": (34.435741, -119.872361),     "490": (34.411008, -119.853316),
    "492": (34.413124, -119.690650),     "493": (34.414416, -119.692020),
    "504": (34.414608, -119.685576),     "505": (34.415369, -119.679654),
    "506": (34.416358, -119.674929),     "508": (34.416883, -119.672110),
    "509": (34.418077, -119.667842),     "510": (34.417478, -119.668100),
    "511": (34.415030, -119.684094),     "512": (34.413158, -119.688330),
    "513": (34.411036, -119.690769),     "514": (34.409036, -119.692993),
    "515": (34.408168, -119.693588),     "518": (34.422531, -119.630277),
    "520": (34.432800, -119.830705),     "521": (34.427146, -119.830610),
    "523": (34.419670, -119.835120),     "529": (34.450005, -119.765770),
    "530": (34.449883, -119.770260),     "531": (34.452036, -119.776179),
    "533": (34.451574, -119.796566),     "534": (34.451642, -119.800150),
    "535": (34.453176, -119.808505),     "536": (34.453042, -119.813550),
    "537": (34.452420, -119.817929),     "538": (34.451442, -119.821191),
    "539": (34.451374, -119.825129),     "540": (34.451072, -119.844604),
    "542": (34.448405, -119.850260),     "543": (34.445840, -119.855827),
    "544": (34.440855, -119.875187),     "546": (34.451377, -119.837876),
    "547": (34.451039, -119.823858),     "548": (34.452818, -119.810923),
    "549": (34.451940, -119.776444),     "550": (34.449353, -119.766952),
    "551": (34.446943, -119.751138),     "580": (34.436895, -119.626323),
    "581": (34.438124, -119.624600),     "582": (34.430748, -119.714423),
    "584": (34.438970, -119.725208),     "590": (34.437171, -119.880469),
    "603": (34.414525, -119.866320),     "606": (34.414270, -119.862900),
    "608": (34.414109, -119.858919),     "609": (34.439745, -119.880625),
    "610": (34.421449, -119.699338),     "611": (34.436872, -119.880626),
    "613": (34.423324, -119.701908),     "615": (34.430595, -119.696870),
    "616": (34.431354, -119.695870),     "618": (34.426674, -119.700830),
    "620": (34.429108, -119.720197),     "621": (34.430440, -119.721815),
    "625": (34.439700, -119.892890),     "626": (34.437493, -119.892808),
    "627": (34.409306, -119.692418),     "628": (34.411304, -119.690062),
    "629": (34.416818, -119.671490),     "630": (34.417197, -119.669602),
    "631": (34.416208, -119.674942),     "632": (34.425593, -119.751145),
    "635": (34.441368, -119.824360),     "636": (34.441126, -119.823570),
    "637": (34.441336, -119.768668),     "638": (34.441071, -119.818650),
    "641": (34.441717, -119.815040),     "642": (34.441962, -119.795831),
    "643": (34.441350, -119.765170),     "647": (34.416678, -119.858631),
    "651": (34.415801, -119.712188),     "652": (34.418829, -119.716366),
    "653": (34.413663, -119.709300),     "655": (34.422341, -119.721157),
    "656": (34.417592, -119.714690),     "660": (34.436617, -119.898376),
    "662": (34.390780, -119.506561),     "663": (34.390717, -119.506761),
    "664": (34.393057, -119.511234),     "665": (34.400487, -119.520333),
    "667": (34.417825, -119.705588),     "668": (34.411297, -119.715355),
    "670": (34.451324, -119.819789),     "671": (34.452323, -119.817751),
    "672": (34.448477, -119.849833),     "673": (34.449664, -119.770187),
    "674": (34.440864, -119.873883),     "675": (34.452850, -119.813430),
    "676": (34.445670, -119.855776),     "677": (34.451486, -119.800590),
    "678": (34.451431, -119.796469),     "679": (34.451194, -119.837189),
    "680": (34.451485, -119.790789),     "681": (34.450926, -119.844361),
    "683": (34.451174, -119.759761),     "684": (34.451181, -119.759940),
    "685": (34.448060, -119.759580),     "686": (34.447944, -119.759760),
    "689": (34.402765, -119.707811),     "691": (34.421415, -119.648180),
    "693": (34.421014, -119.644010),     "694": (34.411246, -119.701558),
    "696": (34.421081, -119.693328),     "699": (34.425045, -119.689166),
    "700": (34.419373, -119.695157),     "701": (34.443896, -119.779060),
    "702": (34.443758, -119.779136),     "703": (34.444594, -119.780470),
    "704": (34.443035, -119.777906),     "705": (34.443036, -119.778007),
    "706": (34.428940, -119.689475),     "707": (34.424829, -119.693849),
    "708": (34.425025, -119.693469),     "709": (34.426909, -119.691627),
    "710": (34.427136, -119.691232),     "711": (34.425881, -119.692732),
    "713": (34.439162, -119.620731),     "714": (34.436108, -119.640962),
    "715": (34.438116, -119.610185),     "716": (34.436956, -119.632321),
    "717": (34.438780, -119.612877),     "719": (34.416898, -119.853300),
    "720": (34.433708, -119.884987),     "721": (34.441833, -119.827780),
    "722": (34.442820, -119.828160),     "726": (34.443274, -119.830553),
    "727": (34.427112, -119.830390),     "728": (34.433392, -119.830486),
    "730": (34.451595, -119.757295),     "752": (34.439300, -119.774186),
    "753": (34.429823, -119.883074),     "754": (34.430160, -119.862874),
    "755": (34.432640, -119.841502),     "756": (34.429695, -119.890464),
    "761": (34.434982, -119.802570),     "765": (34.435821, -119.641420),
    "766": (34.433200, -119.640950),     "767": (34.432600, -119.640780),
    "771": (34.451623, -119.751161),     "772": (34.454905, -119.751177),
    "773": (34.425859, -119.735344),     "774": (34.435670, -119.733539),
    "776": (34.421575, -119.602367),     "778": (34.418655, -119.590435),
    "788": (34.408498, -119.720905),     "789": (34.405776, -119.721040),
    "795": (34.426462, -119.707922),     "810": (34.425584, -119.733549),
    "811": (34.435676, -119.751670),     "814": (34.440314, -119.727960),
    "816": (34.426886, -119.709439),     "819": (34.436151, -119.722109),
    "823": (34.440345, -119.746336),     "824": (34.440319, -119.758847),
    "825": (34.412955, -119.690115),     "829": (34.433429, -119.718382),
    "830": (34.435289, -119.720929),     "831": (34.440325, -119.739774),
    "834": (34.410890, -119.853462),     "836": (34.421903, -119.640040),
    "838": (34.428640, -119.640856),     "839": (34.423941, -119.640254),
    "840": (34.428730, -119.640732),     "843": (34.447855, -119.760640),
    "846": (34.410534, -119.699714),     "847": (34.427411, -119.798720),
    "848": (34.428081, -119.795769),     "856": (34.437079, -119.895155),
    "858": (34.442538, -119.797363),     "861": (34.432328, -119.733450),
    "863": (34.412529, -119.705000),     "864": (34.426394, -119.631460),
    "865": (34.414055, -119.691950),     "867": (34.432986, -119.631880),
    "868": (34.429185, -119.631550),     "871": (34.431662, -119.604609),
    "872": (34.423783, -119.613150),     "876": (34.419003, -119.869570),
    "877": (34.426371, -119.869870),     "879": (34.423789, -119.869860),
    "884": (34.422514, -119.750308),     "885": (34.425021, -119.747420),
    "887": (34.431015, -119.732000),     "889": (34.446147, -119.789722),
    "890": (34.445370, -119.807240),     "891": (34.445226, -119.803329),
    "892": (34.428090, -119.711089),     "893": (34.445126, -119.797221),
    "898": (34.447595, -119.760510),     "899": (34.445181, -119.760550),
    "900": (34.445351, -119.760350),     "902": (34.411026, -119.551985),
    "903": (34.407072, -119.547339),     "904": (34.416497, -119.561450),
    "905": (34.415060, -119.558047),     "907": (34.416662, -119.569033),
    "908": (34.404520, -119.527596),     "909": (34.415785, -119.576076),
    "910": (34.417449, -119.584224),     "912": (34.405118, -119.534935),
    "914": (34.426878, -119.802372),     "919": (34.431780, -119.692970),
    "920": (34.422338, -119.680071),     "922": (34.427748, -119.727050),
    "925": (34.435796, -119.821150),     "926": (34.437692, -119.783930),
    "927": (34.435391, -119.796320),     "928": (34.430292, -119.868730),
    "929": (34.429796, -119.897653),     "930": (34.435141, -119.816373),
    "931": (34.430724, -119.853635),     "932": (34.430470, -119.860405),
    "933": (34.401852, -119.723022),     "939": (34.423659, -119.640085),
    "940": (34.443739, -119.788345),     "941": (34.443651, -119.788596),
    "942": (34.441237, -119.819380),     "943": (34.450805, -119.847155),
    "944": (34.423279, -119.702191),     "945": (34.424820, -119.700580),
    "946": (34.424741, -119.698688),     "947": (34.423547, -119.697049),
    "948": (34.423995, -119.694548),     "949": (34.422070, -119.651990),
    "950": (34.421153, -119.622639),     "952": (34.419746, -119.676150),
    "953": (34.423915, -119.697363),     "954": (34.404804, -119.532571),
    "955": (34.419670, -119.594537),     "956": (34.404743, -119.529420),
    "958": (34.430158, -119.877910),     "959": (34.429982, -119.886619),
    "960": (34.430995, -119.905480),     "961": (34.415399, -119.681190),
    "963": (34.425152, -119.835440),     "965": (34.419703, -119.835300),
    "966": (34.425008, -119.835200),     "1001": (34.452776, -119.779570),
    "1003": (34.453013, -119.807700),     "1023": (34.414872, -119.839620),
    "1024": (34.450067, -119.765250),     "1025": (34.450914, -119.790320),
    "1036": (34.448666, -119.830779),     "1037": (34.445966, -119.830775),
    "1044": (34.435311, -119.814560),     "1045": (34.435018, -119.813179),
    "1052": (34.411870, -119.857582),     "1053": (34.411753, -119.857340),
    "1054": (34.410741, -119.856187),     "1055": (34.410651, -119.856298),
    "1056": (34.414222, -119.859040),     "1063": (34.417498, -119.857450),
    "1064": (34.417513, -119.861260),     "1065": (34.417245, -119.861150),
    "1066": (34.417241, -119.857850),     "1069": (34.417575, -119.865430),
    "1081": (34.442962, -119.828330),     "1082": (34.424735, -119.726180),
    "1084": (34.427596, -119.746720),     "1085": (34.444241, -119.758900),
    "1086": (34.409457, -119.695892),     "1089": (34.386014, -119.489400),
    "1100": (34.441411, -119.891964),     "1102": (34.430184, -119.873870),
    "1104": (34.438929, -119.789490),     "1110": (34.405195, -119.738485),
    "1111": (34.427687, -119.739112),     "1117": (34.429180, -119.723538),
    "1120": (34.415404, -119.847934),     "1121": (34.414983, -119.839624),
    "1122": (34.429195, -119.725335),     "1123": (34.429764, -119.722713),
    "1124": (34.440580, -119.744017),     "1125": (34.433052, -119.855264),
    "1126": (34.433254, -119.855469)
]

/// Looks up coordinates for a stop code from the embedded stop coordinate dictionary.
func lookupStopCoordinates(stopCode: String) -> (lat: Double, lon: Double)? {
    return embeddedStopCoordinates[stopCode]
}

// MARK: - Vehicle locations model

struct VehicleLocation: Identifiable, Equatable {
    let id: String
    let routeID: String?
    let tripID: String?
    let latitude: Double
    let longitude: Double
    let bearing: Double?
    let speedMetersPerSecond: Double?
    let timestamp: Date?

    var coordinates: (Double, Double) { (latitude, longitude) }
}

// MARK: - Vehicle ID matching helpers

func normalizeVehicleID(_ s: String) -> String {
    let allowed = s.unicodeScalars.filter { CharacterSet.alphanumerics.contains($0) }
    return String(String.UnicodeScalarView(allowed)).uppercased()
}

func matchVehicle(by vehicleID: String, in vehicles: [VehicleLocation]) -> VehicleLocation? {
    let target = normalizeVehicleID(vehicleID)
    guard !target.isEmpty else { return nil }
    return vehicles.first(where: { normalizeVehicleID($0.id) == target })
}

// MARK: - GTFS-RT Protobuf Internals

private let _iso8601Fractional: ISO8601DateFormatter = {
    let f = ISO8601DateFormatter()
    f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    return f
}()

private func debugDumpVehicles(_ vehicles: [VehicleLocation]) {
#if DEBUG
    print("\n===== GTFS-RT VehiclePositions decoded: \(vehicles.count) vehicles =====")
    for v in vehicles {
        let ts = v.timestamp.map { _iso8601Fractional.string(from: $0) } ?? "nil"
        let bearingStr = v.bearing.map { String(format: "%.0f°", $0) } ?? "nil"
        let speedMS = v.speedMetersPerSecond.map { String(format: "%.1f m/s", $0) } ?? "nil"
        let speedMPH = v.speedMetersPerSecond.map { String(format: "%.1f mph", $0 * 2.236936) } ?? "nil"
        let latStr = String(format: "%.6f", v.latitude)
        let lonStr = String(format: "%.6f", v.longitude)
        print("id=\(v.id) route=\(v.routeID ?? "nil") trip=\(v.tripID ?? "nil") lat=\(latStr) lon=\(lonStr) bearing=\(bearingStr) speed=\(speedMS) (\(speedMPH)) ts=\(ts)")
    }
    print("===== END GTFS-RT dump =====\n")
#endif
}

// Internal message models (minimal GTFS-RT subset)
private struct Position { var latitude: Double?; var longitude: Double?; var bearing: Double?; var speed: Double? }
private struct TripDescriptor { var tripID: String?; var routeID: String? }
private struct VehicleDescriptor { var id: String? }
private struct VehiclePositionMessage { var trip: TripDescriptor?; var position: Position?; var vehicle: VehicleDescriptor?; var timestamp: UInt64? }
private struct FeedEntity { var id: String?; var vehicle: VehiclePositionMessage? }

// Minimal Protobuf reader
private struct ProtobufReader {
    let data: Data
    private(set) var offset: Int = 0
    var isAtEnd: Bool { offset >= data.count }
    init(data: Data) { self.data = data }
    mutating func readVarint() -> UInt64? {
        var result: UInt64 = 0
        var shift: UInt64 = 0
        while offset < data.count && shift < 64 {
            let byte = data[offset]
            offset += 1
            result |= UInt64(byte & 0x7F) << shift
            if (byte & 0x80) == 0 { return result }
            shift += 7
        }
        return nil
    }
    mutating func readFixed32() -> UInt32? {
        guard offset + 4 <= data.count else { return nil }
        let slice = data[offset ..< offset + 4]
        offset += 4
        var value: UInt32 = 0
        for (i, b) in slice.enumerated() { value |= UInt32(b) << (8 * i) }
        return value
    }
    mutating func readLengthDelimited() -> Data? {
        guard let len64 = readVarint() else { return nil }
        let len = Int(len64)
        guard offset + len <= data.count else { return nil }
        let sub = data.subdata(in: offset ..< offset + len)
        offset += len
        return sub
    }
    mutating func readString() -> String? { guard let bytes = readLengthDelimited() else { return nil }; return String(data: bytes, encoding: .utf8) }
    mutating func readKey() -> (fieldNumber: Int, wireType: Int)? {
        guard let key = readVarint() else { return nil }
        let wireType = Int(key & 0x7)
        let fieldNumber = Int(key >> 3)
        return (fieldNumber, wireType)
    }
    mutating func skipField(wireType: Int) {
        switch wireType {
        case 0: _ = readVarint()
        case 1: offset = min(data.count, offset + 8)
        case 2: if let len64 = readVarint() { let len = Int(len64); offset = min(data.count, offset + len) }
        case 5: offset = min(data.count, offset + 4)
        default: break
        }
    }
}

// Parsers for GTFS-RT subset
private func parsePosition(_ data: Data) -> Position {
    var reader = ProtobufReader(data: data)
    var position = Position()
    while let (field, wire) = reader.readKey() {
        switch field {
        case 1: // latitude (float, fixed32)
            if wire == 5, let bits = reader.readFixed32() { position.latitude = Double(Float(bitPattern: bits)) } else { reader.skipField(wireType: wire) }
        case 2: // longitude (float, fixed32)
            if wire == 5, let bits = reader.readFixed32() { position.longitude = Double(Float(bitPattern: bits)) } else { reader.skipField(wireType: wire) }
        case 3: // bearing (float, fixed32)
            if wire == 5, let bits = reader.readFixed32() { position.bearing = Double(Float(bitPattern: bits)) } else { reader.skipField(wireType: wire) }
        case 4: // odometer (double, fixed64) — not used here; skip
            reader.skipField(wireType: wire)
        case 5: // speed (float, fixed32)
            if wire == 5, let bits = reader.readFixed32() { position.speed = Double(Float(bitPattern: bits)) } else { reader.skipField(wireType: wire) }
        default:
            reader.skipField(wireType: wire)
        }
    }
    return position
}

private func parseTripDescriptor(_ data: Data) -> TripDescriptor {
    var reader = ProtobufReader(data: data)
    var trip = TripDescriptor()
    while let (field, wire) = reader.readKey() {
        switch field {
        case 1: if wire == 2 { trip.tripID = reader.readString() } else { reader.skipField(wireType: wire) }
        case 5: if wire == 2 { trip.routeID = reader.readString() } else { reader.skipField(wireType: wire) }
        default: reader.skipField(wireType: wire)
        }
    }
    return trip
}

private func parseVehicleDescriptor(_ data: Data) -> VehicleDescriptor {
    var reader = ProtobufReader(data: data)
    var vehicle = VehicleDescriptor()
    while let (field, wire) = reader.readKey() {
        switch field {
        case 1: if wire == 2 { vehicle.id = reader.readString() } else { reader.skipField(wireType: wire) }
        default: reader.skipField(wireType: wire)
        }
    }
    return vehicle
}

private func parseVehiclePosition(_ data: Data) -> VehiclePositionMessage {
    var reader = ProtobufReader(data: data)
    var vp = VehiclePositionMessage()
    while let (field, wire) = reader.readKey() {
        switch field {
        case 1: // trip
            if wire == 2, let sub = reader.readLengthDelimited() { vp.trip = parseTripDescriptor(sub) } else { reader.skipField(wireType: wire) }
        case 2: // position
            if wire == 2, let sub = reader.readLengthDelimited() { vp.position = parsePosition(sub) } else { reader.skipField(wireType: wire) }
        case 5: // timestamp (varint)
            if wire == 0, let ts = reader.readVarint() { vp.timestamp = ts } else { reader.skipField(wireType: wire) }
        case 8: // vehicle descriptor
            if wire == 2, let sub = reader.readLengthDelimited() { vp.vehicle = parseVehicleDescriptor(sub) } else { reader.skipField(wireType: wire) }
        default:
            reader.skipField(wireType: wire)
        }
    }
    return vp
}

private func parseFeedEntity(_ data: Data) -> FeedEntity {
    var reader = ProtobufReader(data: data)
    var entity = FeedEntity()
    while let (field, wire) = reader.readKey() {
        switch field {
        case 1: // id
            if wire == 2 { entity.id = reader.readString() } else { reader.skipField(wireType: wire) }
        case 4: // vehicle (length-delimited, field 4)
            if wire == 2, let sub = reader.readLengthDelimited() { entity.vehicle = parseVehiclePosition(sub) } else { reader.skipField(wireType: wire) }
        default:
            reader.skipField(wireType: wire)
        }
    }
    return entity
}

// Public decoder
enum GTFSRTManualDecoder {
    static func decodeVehicles(from data: Data) -> [VehicleLocation] {
        var reader = ProtobufReader(data: data)
        var locations: [VehicleLocation] = []
        while let (field, wire) = reader.readKey() {
            if field == 2 && wire == 2, let entityData = reader.readLengthDelimited() {
                let entity = parseFeedEntity(entityData)
                guard let vp = entity.vehicle, let pos = vp.position, let lat = pos.latitude, let lon = pos.longitude else { continue }
                let vehID = vp.vehicle?.id ?? entity.id ?? ""
                let routeID = vp.trip?.routeID
                let tripID = vp.trip?.tripID
                let bearing = pos.bearing
                let speed = pos.speed
                let tsDate: Date? = vp.timestamp.map { Date(timeIntervalSince1970: TimeInterval($0)) }
                let location = VehicleLocation(id: vehID, routeID: routeID, tripID: tripID, latitude: lat, longitude: lon, bearing: bearing, speedMetersPerSecond: speed, timestamp: tsDate)
                locations.append(location)
            } else {
                reader.skipField(wireType: wire)
            }
        }
        return locations
    }
}

// Optional: gunzip helper for raw gzip payloads without Content-Encoding
private func gunzipIfNeeded(_ data: Data) -> Data {
    // gzip magic header 0x1f 0x8b
    guard data.count >= 2, data[0] == 0x1f, data[1] == 0x8b else { return data }

    var decoded = Data()

    var stream = compression_stream(dst_ptr: UnsafeMutablePointer<UInt8>(bitPattern: 0)!, dst_size: 0, src_ptr: UnsafePointer<UInt8>(bitPattern: 0)!, src_size: 0, state: nil)
    var status = compression_stream_init(&stream, COMPRESSION_STREAM_DECODE, COMPRESSION_ZLIB)
    guard status != COMPRESSION_STATUS_ERROR else { return data }
    defer { compression_stream_destroy(&stream) }

    return data.withUnsafeBytes { (srcBuf: UnsafeRawBufferPointer) in
        var srcIndex = 0
        decoded.removeAll(keepingCapacity: true)

        while srcIndex < data.count {
            let srcChunk = min(64 * 1024, data.count - srcIndex)
            stream.src_ptr = srcBuf.baseAddress!.advanced(by: srcIndex).assumingMemoryBound(to: UInt8.self)
            stream.src_size = srcChunk
            srcIndex += srcChunk

            var dstData = Data(count: 64 * 1024)
            dstData.withUnsafeMutableBytes { dstBuf in
                stream.dst_ptr = dstBuf.baseAddress!.assumingMemoryBound(to: UInt8.self)
                stream.dst_size = dstBuf.count

                while true {
                    status = compression_stream_process(&stream, srcIndex >= data.count ? Int32(COMPRESSION_STREAM_FINALIZE.rawValue) : 0)
                    let produced = dstBuf.count - stream.dst_size
                    if produced > 0 {
                        if let base = dstBuf.bindMemory(to: UInt8.self).baseAddress { decoded.append(base, count: produced) }
                        stream.dst_ptr = dstBuf.baseAddress!.assumingMemoryBound(to: UInt8.self)
                        stream.dst_size = dstBuf.count
                    }
                    if status == COMPRESSION_STATUS_OK && stream.src_size == 0 {
                        break // need more input
                    } else if status == COMPRESSION_STATUS_END {
                        return
                    } else if status == COMPRESSION_STATUS_ERROR {
                        decoded.removeAll()
                        return
                    }
                }
            }
        }
        return decoded.isEmpty ? data : decoded
    }
}

final class MTDVehicleService {
    private let session: URLSession
    init(session: URLSession = .shared) { self.session = session }
    func fetchVehicleLocations(from url: URL, completion: @escaping (Result<[VehicleLocation], Error>) -> Void) {
        let task = session.dataTask(with: url) { data, response, error in
            if let error = error { completion(.failure(error)); return }
#if DEBUG
            if let http = response as? HTTPURLResponse {
                let lenHeader = http.value(forHTTPHeaderField: "Content-Length") ?? "(none)"
                print("GTFS-RT fetch: status=\(http.statusCode) mime=\(http.mimeType ?? "nil") content-length=\(lenHeader)")
            } else {
                print("GTFS-RT fetch: non-HTTP response")
            }
#endif
            guard let data = data else {
                let err = NSError(domain: "MTDVehicleService", code: -1, userInfo: [NSLocalizedDescriptionKey: "No data"])
                completion(.failure(err)); return
            }

            // Try decode as-is
            var vehicles = GTFSRTManualDecoder.decodeVehicles(from: data)

            // Fallback: gunzip if the payload appears to be gzipped without Content-Encoding
            if vehicles.isEmpty {
                let unzipped = gunzipIfNeeded(data)
                if unzipped != data {
                    vehicles = GTFSRTManualDecoder.decodeVehicles(from: unzipped)
                }
            }

#if DEBUG
            if vehicles.isEmpty {
                let prefix = data.prefix(24)
                print("GTFS-RT decode yielded 0 vehicles. First 24 bytes: \(prefix.map { String(format: "%02x", $0) }.joined(separator: " "))")
            }
            debugDumpVehicles(vehicles)
#endif
            completion(.success(vehicles))
        }
        task.resume()
    }
}

// MARK: - Config
enum Routes: String, CaseIterable {
    case r1 = "1"
    case r2 = "2"
    case r3 = "3"
    case r4 = "4"
    case r5 = "5"
    case r6 = "6"
    case r7 = "7"
    case r11 = "11"
    case r12X = "12X"
    case r14 = "14"
    case r15X = "15X"
    case r16 = "16"
    case r17 = "17"
    case r19X = "19X"
    case r20 = "20"
    case r23 = "23"
    case r24X = "24X"
    case r25 = "25"
    case r27 = "27"
    case r28 = "28"
}

import SwiftUI

/// Route colors matching official SBMTD branding
func sbmtdRouteColor(for route: String) -> Color {
    switch route {
    case "1":   return Color(red: 180/255, green: 37/255,  blue: 101/255)
    case "2":   return Color(red: 180/255, green: 37/255,  blue: 101/255)
    case "3":   return Color(red: 133/255, green: 189/255, blue: 86/255)
    case "4":   return Color(red: 126/255, green: 203/255, blue: 241/255)
    case "5":   return Color(red: 225/255, green: 127/255, blue: 172/255)
    case "6":   return Color(red: 217/255, green: 57/255,  blue: 52/255)
    case "7":   return Color(red: 71/255,  green: 146/255, blue: 205/255)
    case "11":  return Color(red: 217/255, green: 57/255,  blue: 52/255)
    case "12X": return Color(red: 172/255, green: 125/255, blue: 77/255)
    case "14":  return Color(red: 118/255, green: 78/255,  blue: 39/255)
    case "15X": return Color(red: 61/255,  green: 138/255, blue: 76/255)
    case "16":  return Color(red: 115/255, green: 118/255, blue: 120/255)
    case "17":  return Color(red: 248/255, green: 215/255, blue: 73/255)
    case "19X": return Color(red: 168/255, green: 153/255, blue: 214/255)
    case "20":  return Color(red: 227/255, green: 125/255, blue: 96/255)
    case "23":  return Color(red: 125/255, green: 203/255, blue: 242/255)
    case "24X": return Color(red: 171/255, green: 124/255, blue: 77/255)
    case "25":  return Color(red: 76/255,  green: 77/255,  blue: 79/255)
    case "27":  return Color(red: 122/255, green: 32/255,  blue: 116/255)
    case "28":  return Color(red: 66/255,  green: 147/255, blue: 212/255)
    default:    return Color.gray
    }
}

struct Stop: Identifiable, Hashable {
    let id: String        // SBMTD BusTracker stop id
    let label: String     // UI label
    let purpose: Purpose
    enum Purpose { case storkeAndSierraMadre, ucsbElings, ucsbNorthHall, custom }
}

// MARK: - Models
struct StopBoard: Identifiable, Hashable {
    let id = UUID()
    let stop: Stop
    let predictions: [Prediction]
    let fetchedAt: Date
}

struct Prediction: Identifiable, Hashable {
    let id = UUID()
    let route: String       // e.g. "11", "27", "28", "24X"
    let headsign: String    // e.g. "UCSB North Hall", "Downtown SB", "Camino Real Mkt"
    let minutes: Int?       // nil if not parsable; 0 for APPROACHING/DUE
    let vehicleID: String?
}

// MARK: - Provider abstraction
protocol DeparturesProvider {
    func fetch(stopId: String) async throws -> [Prediction]
}

// MARK: - SBMTD BusTracker HTML provider (no key required)
// Endpoint pattern: https://bustracker.sbmtd.gov/bustime/wireless/html/eta.jsp?route=---&direction=---&displaydirection=---&stop=---&findstop=on&selectedRtpiFeeds=&id=STOPID
// We parse simple "#<route> <headsign> <N MIN | APPROACHING | DUE>" rows.
final class SBMTDBusTrackerProvider: DeparturesProvider {
    func fetch(stopId: String) async throws -> [Prediction] {
        // Request the full departure board by stop ID using the canonical query shape.
        let url = URL(string: "https://bustracker.sbmtd.gov/bustime/wireless/html/eta.jsp?route=---&direction=---&displaydirection=---&stop=---&findstop=on&selectedRtpiFeeds=&id=\(stopId)")!
        let (data, response) = try await URLSession.shared.data(from: url)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode),
              let html = String(data: data, encoding: .utf8), !html.isEmpty else {
            return []
        }

        let predictions = parse(html: html)
        return predictions
    }

    private func parse(html: String) -> [Prediction] {
        // Extremely lightweight parsing: look for blocks that start with "##  #" and then capture route, headsign, minutes.
        // Example snippets:
        //   ##  #28  UCSB North Hall   5 MIN
        //   ##  #11  Downtown SB   APPROACHING
        //   ##  #24X  UCSB / Camino Real Mkt   19 MIN
        var results: [Prediction] = []

        // Normalize whitespace to simplify regex.
        let squished = html.replacingOccurrences(of: "\r", with: "")
            .replacingOccurrences(of: "&nbsp;", with: " ")
            .replacingOccurrences(of: "\n\n", with: "\n")

        let text = squished.replacingOccurrences(of: "<[^>]+>", with: " ", options: .regularExpression)

        // Extract vehicle annotations in order of appearance per route
        // e.g., lines contain "(Vehicle 708)" or just "SCH" on a following line.
        // We'll build a per-route queue we can pop from as we collect predictions.
        var vehicleQueues: [String: [String]] = [:]
        do {
            let routeRx = try? NSRegularExpression(pattern: "#\\s*#?([0-9]{1,2}X?)", options: [.caseInsensitive])
            let vehicleRx = try? NSRegularExpression(pattern: "\\((?:Vehicle\\s+)?([A-Z0-9]+)\\)", options: [.caseInsensitive])
            // Split by <h2> sections to maintain order
            let sections = squished.components(separatedBy: "<h2>")
            for sec in sections {
                // Find the route tag within the section
                let ns = sec as NSString
                if let routeRx = routeRx, let m = routeRx.firstMatch(in: sec, range: NSRange(location: 0, length: ns.length)) {
                    let route = ns.substring(with: m.range(at: 1)).uppercased()
                    var vID: String? = nil
                    if let vehicleRx = vehicleRx, let vm = vehicleRx.firstMatch(in: sec, range: NSRange(location: 0, length: ns.length)) {
                        vID = ns.substring(with: vm.range(at: 1)).uppercased()
                    } else if sec.range(of: ">\n\n    \n    \n    &nbsp;SCH", options: .caseInsensitive) != nil || sec.range(of: ">SCH<", options: .caseInsensitive) != nil || sec.localizedCaseInsensitiveContains("SCH") {
                        vID = "SCH"
                    }
                    if let vID = vID {
                        vehicleQueues[route, default: []].append(vID)
                    }
                }
            }
        }

        // Two regex patterns for different formats:
        let pattern1 = "#\\s*#?([0-9]{1,2}X?)\\s+([^\\n\\r]+?)\\s+(APPROACHING|DUE|ARRIVING|\\d+\\s*MIN\\w*)"
        let pattern2 = "(?m)^\\s*([0-9]{1,2}X?)\\s+([^\\n\\r]+?)\\s+(APPROACHING|DUE|ARRIVING|\\d+\\s*MIN\\w*)"

        func collect(using pattern: String) {
            guard let rx = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) else { return }
            let ns = text as NSString
            let matches = rx.matches(in: text, options: [], range: NSRange(location: 0, length: ns.length))
            for m in matches {
                guard m.numberOfRanges >= 4 else { continue }
                let route = ns.substring(with: m.range(at: 1)).uppercased()
                var headsign = ns.substring(with: m.range(at: 2)).trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
                headsign = headsign.replacingOccurrences(of: "\u{00A0}", with: " ")
                let rawMin = ns.substring(with: m.range(at: 3)).uppercased()

                let minutes: Int?
                if rawMin.contains("APPROACHING") || rawMin.contains("DUE") || rawMin.contains("ARRIVING") { minutes = 0 }
                else {
                    // Extract first integer found (handles MIN, MINS, MINUTES, etc.)
                    if let dig = rawMin.range(of: "[0-9]+", options: .regularExpression) {
                        minutes = Int(rawMin[dig])
                    } else { minutes = nil }
                }

                let vID: String? = {
                    if var q = vehicleQueues[route], !q.isEmpty {
                        let first = q.removeFirst()
                        vehicleQueues[route] = q
                        return first
                    }
                    return nil
                }()
                results.append(.init(route: route, headsign: headsign, minutes: minutes, vehicleID: vID))
            }
        }
        collect(using: pattern1)
        if results.isEmpty { collect(using: pattern2) }

#if DEBUG
        if results.isEmpty {
            let preview = text.count > 600 ? String(text.prefix(600)) + "…" : text
            print("SBMTD parse: no matches found; text preview: \(preview)")
        }
#endif
        return results
    }
}

// MARK: - Direction filter heuristics
func towardStorkeElColegio(_ p: Prediction) -> Bool {
    // We want trips heading toward the Storke & El Colegio area.
    // Common headsigns that move in that direction: "UCSB", "Camino Real", "Isla Vista", "Storke", "Marketplace".
    let h = p.headsign.lowercased()
    return h.contains("ucsb") || h.contains("camino real") || h.contains("isla vista") || h.contains("storke") || h.contains("market")
}

func towardCaminoRealMarket(_ p: Prediction) -> Bool {
    // Strictly prefer trips heading toward Camino Real Market / Marketplace.
    // Common headsign variants observed: "Camino Real", "Camino Real Mkt", "Camino Real Market", "Marketplace".
    let h = p.headsign.lowercased()
    return h.contains("camino real mkt") || h.contains("marketplace") || h.contains("market") || h.contains("mkt")
}
